apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-service
  namespace: default
  labels:
    app: data-ingest
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: data-ingest
  type: LoadBalancer
  loadBalancerIP: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingest
spec:
  selector:
    matchLabels:
      app: data-ingest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: data-ingest
    spec:
      containers:
      - image: ue2padvaiwacr32.azurecr.io/docflask:v1
        name: data-ingest
        ports:
        - containerPort: 5000
          name: data-ingest
